### ISSUE TITLE
docker-compose up failed

### ISSUE THREAD

**Issue by Hanochhu** [OpenBMB/XAgent#119]
## Issue Description / 问题描述
when I run "docker-compose up", there is an ERROR. 
"The Compose file './../docker-compose.yml' is invalid because:
networks.default value Additional properties are not allowed ('name' was unexpected)"

## Steps to Reproduce / 复现步骤
download this project, run "cd ToolServer" then run "docker-compose up" in terminal.

## Expected Behavior / 预期行为
Get docker stuff right

## Environment / 环境信息
- Operating System / 操作系统：wsl ubuntu20.04
- Python Version / Python 版本：3.10.13
- Other Relevant Information / 其他相关信息：Docker version 24.0.6    docker-compose version 1.25.0

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
<img width="878" alt="image" src="https://github.com/OpenBMB/XAgent/assets/52187558/fd14bd57-471a-4128-8fa0-ccfb1056fb04">

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

I sure the project is fetched to latest.
It seems that can't read variable in ".env" file  also?

**Comment by sailaoda** [comment]
hello, you could fetch to latest project and try again. If it happens again, you can try to

**Comment by sailaoda** [comment]
Hello, thanks for your issue, you could fetch to latest project and try again, and run "docker-compose up" to see what is happening.

**Comment by Hanochhu** [comment]
> Hello, thanks for your issue, you could fetch to latest project and try again, and run "docker-compose up" to see what is happening.

it seems that something wrong because I use WSL but didn't use docker desktop? I use docker in WSL as other normal ubuntu system rather than install a docker desktop in windows.
And the variable in .env still don't work

<img width="1006" alt="image" src="https://github.com/OpenBMB/XAgent/assets/52187558/9ac104e7-9f12-4bf2-b9cc-5da30580c9fc">

**Comment by sailaoda** [comment]
Hello, as your description, please check whether there is a Docker Desktop on your host Windows, if there is ,maybe it happened about the env problem.

If you don't have Docker Desktop installed on Windows and you're encountering the "docker-credential-desktop.exe not installed or not available in PATH" error when running docker-compose up in WSL, you should not be experiencing this issue since it is typically related to Docker Desktop.

If you are still encountering Docker-related issues in WSL, you can try the following steps to resolve the problem:

Ensure Docker is Properly Installed in WSL: First, make sure you have installed Docker within WSL. You can follow the official Docker documentation to install Docker to ensure the correct installation and configuration.

Restart WSL: Sometimes, restarting the WSL subsystem can resolve some Docker-related issues. You can restart WSL by running the following command in the Windows terminal:

```bash
wsl --shutdown
```
After that, try running Docker commands again.

Check Docker Configuration: Ensure that your Docker configuration is correct. You can check the configuration file for the Docker daemon, usually located at /etc/docker/daemon.json. Make sure there are no errors in the configuration and make corrections if necessary.

Check Docker Installation: Sometimes, Docker installation can go wrong, leading to Docker-related errors. Try reinstalling Docker and make sure you use the correct installation method.

If you're still facing issues, it's advisable to provide more error information or logs to better understand the root cause of the problem. This will make it easier to find a solution.

**Comment by Hanochhu** [comment]
> Hello, as your description, please check whether there is a Docker Desktop on your host Windows, if there is ,maybe it happened about the env problem.
> 
> If you don't have Docker Desktop installed on Windows and you're encountering the "docker-credential-desktop.exe not installed or not available in PATH" error when running docker-compose up in WSL, you should not be experiencing this issue since it is typically related to Docker Desktop.
> 
> If you are still encountering Docker-related issues in WSL, you can try the following steps to resolve the problem:
> 
> Ensure Docker is Properly Installed in WSL: First, make sure you have installed Docker within WSL. You can follow the official Docker documentation to install Docker to ensure the correct installation and configuration.
> 
> Restart WSL: Sometimes, restarting the WSL subsystem can resolve some Docker-related issues. You can restart WSL by running the following command in the Windows terminal:
> 
> ```shell
> wsl --shutdown
> ```
> 
> After that, try running Docker commands again.
> 
> Check Docker Configuration: Ensure that your Docker configuration is correct. You can check the configuration file for the Docker daemon, usually located at /etc/docker/daemon.json. Make sure there are no errors in the configuration and make corrections if necessary.
> 
> Check Docker Installation: Sometimes, Docker installation can go wrong, leading to Docker-related errors. Try reinstalling Docker and make sure you use the correct installation method.
> 
> If you're still facing issues, it's advisable to provide more error information or logs to better understand the root cause of the problem. This will make it easier to find a solution.

I fixed this issue by solution of https://stackoverflow.com/questions/67642620/docker-credential-desktop-not-installed-or-not-available-in-path

Thanks for your time! 👍

**Comment by Hanochhu** [comment]
When you commit 8b17c43fd325863be0680ab8a8d90de0e8446671 which delete name: tool-server-network , I can run "docker-compose up" successfully but there is no  "**tool-server-network**" container, hence this project doesn't  work. 

When you rollback in commit 6c04841afa03354cff20b9528d4c396479b12a7b, the issue in the very beginning shows again. 
And I notice your commit message, it's something wrong with my docker version?

**Comment by huruizhi** [comment]
docker-compose --env-file .env up -d

**Comment by 88daxiong** [comment]
change the version to 3.7(the first line in docker-compose.yaml) will solve the problem "name was unexpected".

**Comment by Hanochhu** [comment]
> docker-compose --env-file .env up -d

👍  thank you

**Comment by Hanochhu** [comment]
> change the version to 3.7(the first line in docker-compose.yaml) will solve the problem "name was unexpected".

thank you . it's work

**Comment by Umpire2018** [comment]
1. When using docker-compose up, Docker Compose will automatically look for a file named .env in the project directory  and read the variables from there. @huruizhi 
2. We don't recommend changing base image version. @88daxiong

**Comment by Starfruit007** [comment]
I have encountered with same error, here is the details:

**Error**
networks.default value Additional properties are not allowed ('name' was unexpected)
volumes.toolserverconfig value Additional properties are not allowed ('name' was unexpected)
services.XAgentServer.depends_on contains an invalid type, it should be an array

**Conclusion**
I have installed an old version of docker-compose with command: **apt-get install docker-compose**

**Problem Environment**
Docker version 24.0.2
docker-compose version 1.17.1

[**Solution**](https://blog.csdn.net/pushiqiang/article/details/78682323)

sudo curl -L [https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-`uname](https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-%60uname) -s`-`uname -m` -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose
