### ISSUE TITLE
mysql_native_password is deprecated 

### ISSUE THREAD

**Issue by zhuxiaosheng** [OpenBMB/XAgent#253]
您好，任务执行不动，总是报如下错误

xagent-xagent-mysql-1       | 2023-11-24T13:28:11.463555Z 351 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
adoring_chandrasekhar       | INFO:     127.0.0.1:42862 - "GET / HTTP/1.1" 200 OK
adoring_chandrasekhar       | INFO:     127.0.0.1:42876 - "GET / HTTP/1.1" 200 OK
adoring_chandrasekhar       | INFO:     127.0.0.1:42882 - "GET / HTTP/1.1" 200 OK
adoring_chandrasekhar       | INFO:     127.0.0.1:37002 - "GET / HTTP/1.1" 200 OK
adoring_chandrasekhar       | INFO:     127.0.0.1:37008 - "GET / HTTP/1.1" 200 OK
xagent-xagent-mysql-1       | 2023-11-24T13:28:16.598887Z 352 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
adoring_chandrasekhar       | INFO:     127.0.0.1:37024 - "GET / HTTP/1.1" 200 OK
adoring_chandrasekhar       | INFO:     127.0.0.1:37036 - "GET / HTTP/1.1" 200 OK
adoring_chandrasekhar       | INFO:     127.0.0.1:37044 - "GET / HTTP/1.1" 200 OK
adoring_chandrasekhar       | INFO:     127.0.0.1:37060 - "GET / HTTP/1.1" 200 OK

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
That's not the root cause of server doesn't reponse.

1. Make sure that XAgent-Server finished start-up.
```
INFO:     Stopping reloader process [1]
INFO:     Will watch for changes in these directories: ['/app']
INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using StatReload
INFO:     Started server process [25]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

2. Make sure that you used `docker exec XAgent-Server systemctl start nginx`

3. Make sure when you open the browser, you got these output.
![image](https://github.com/OpenBMB/XAgent/assets/138990495/d3f94f7d-0977-4b38-852e-5a04c2b3a854)

4. Make sure you don't have network issue.
![image](https://github.com/OpenBMB/XAgent/assets/138990495/8d925333-abf9-4fb9-bdd5-3d36e8ad3e12)

Run in 22:30 11/24 CST.
