### ISSUE TITLE
XAgentRunningError: max_workers must be greater than 0 

### ISSUE THREAD

**Issue by YinSonglin1997** [OpenBMB/XAgent#327]
## Issue Description / 问题描述
之前运行都正常，今天再测试时就报Error in task_handler of 7a9315804b0547e58db396fa61b71d60: max_workers must be greater than 0 

## Steps to Reproduce / 复现步骤
[https://github.com/OpenBMB/XAgent/blob/main/XAgentGen/README.md](url)

## Expected Behavior / 预期行为
正常运行

## Environment / 环境信息
- Operating System / 操作系统：Ubuntu 20.04.6 LTS
- Python Version / Python 版本：Python 3.10.0
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
![1702021006818](https://github.com/OpenBMB/XAgent/assets/90330685/2e9c7356-aa1a-4f9f-a886-15a166cb5770)

**Comment by YinSonglin1997** [comment]
请问duckduckgo现在是调用不了了吗？
![1702091813689](https://github.com/OpenBMB/XAgent/assets/90330685/3f289894-a04e-4fd3-9735-7ce731376169)

**Comment by YinSonglin1997** [comment]
升级duckduckgo版本解决

**Comment by Umpire2018** [comment]
> 升级duckduckgo版本解决

请问您是否在建议使用高版本的 `duckduckgo-search` ? 能否开启一个PR？

<img width="859" alt="image" src="https://github.com/OpenBMB/XAgent/assets/138990495/951b8354-df77-40cb-8282-d04ed64e4ec3">

**Comment by YinSonglin1997** [comment]
> > 升级duckduckgo版本解决
> 
> 请问您是否在建议使用高版本的 `duckduckgo-search` ? 能否开启一个PR？
> 
> <img alt="image" width="859" src="https://private-user-images.githubusercontent.com/138990495/289722651-951b8354-df77-40cb-8282-d04ed64e4ec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjk3NzYsIm5iZiI6MTcwMjM2OTQ3NiwicGF0aCI6Ii8xMzg5OTA0OTUvMjg5NzIyNjUxLTk1MWI4MzU0LWRmNzctNDBjYi04MjgyLWQwNGVkNjRlNGVjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwODI0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODZiNTA3NDhlZGM1NjAxMzFjODk1NTQxZGRiZDc3MWYwNWU2N2Q3OTlkN2FkYTI3NTlkZjZiNWEzMmVkNGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t6lijF4HsMDA9Zz0bXr0Evw7WfoA1bjX_XMesmTIeh4">

我将xagentteam/toolserver-node镜像中的duckduckgo-search升级到3.9.10，解决了问题

**Comment by liruixue** [comment]
max_workers must be greater than 0 这个问题和duckduckgo-search版本有关系吗？为啥我这边只看到那个错误，没看到duckduckgo-search的调用异常，而且我的toolserver-node中的duckduckgo-search版本已经到了4.1.0，似乎也不能再升了吧

**Comment by liruixue** [comment]
死到这一步，不知道下一步怎么走呢

**Comment by ttran1904** [comment]
Hello guys!

I believe this issue is related to #344 . 
Basically, the HTTP is not downloaded to the right version (i.e. `httpx[http2]` not `httpx`) and that cause the HTTP response output to be empty. The empty response output makes `max_workers` to be 0.

I'm not sure if this will work on Duckduckgo, but it works for me on the given default files.

**Comment by Umpire2018** [comment]
@ttran1904 @liruixue Can we schedule a meeting so that we can work together to locate the problem?

**Comment by ttran1904** [comment]
Yeah. I'm free right now. Just sent you an email

**Comment by ttran1904** [comment]
Also, if you're gonna use Duckduckgo, I recommend you guys to add duckduckgo-search==<version numer> in the 2 files:

1. ToolServer > ToolServerManager > requirements.txt
2. ToolServer > ToolServerNOde > requirements.txt
and not just `pip install duckduckgo-search` on the local computer, because it's not enough. I think the XAgent specifically uses packages in the Docker container, and the container only has packages specify in requirements.txt.
