### ISSUE TITLE
client error: forbidden for url: http://localhost：8080/get_available_tools

### ISSUE THREAD

**Issue by momaek2023** [OpenBMB/XAgent#343]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
构建docker，执行指令 python run.py --task "1+1等于几" --model "gpt-3.5-turbo-16k" 

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。
输出结果

## Environment / 环境信息
- Operating System / 操作系统：LINUX
- Python Version / Python 版本：3.11.0
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
![错误截图](https://github.com/OpenBMB/XAgent/assets/151289865/68cccfb8-3630-43f9-aca2-811e25805492)

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
An HTTP 403 response code means that a client is forbidden from accessing a valid URL. The server understands the request, but it can't fulfill the request because of client-side issues.

一般情况下，docker 会使用 http://ToolServerManager:8080 来连接同环境下的其他容器。

1. 请确认使用 `docker-compose up` 一次性启动所有容器
2. 确认容器状态正常
