### ISSUE TITLE
web GUI Default Password

### ISSUE THREAD

**Issue by Namec999** [OpenBMB/XAgent#74]
Hello All, 

after installed all the required parts, i am stuck logging into the UI, it's says login Failed when using 

user : admin
password : xagent-admin

is there anything that i miss

best

**Comment by luyaxi** [comment]
Try to pull latest code and rebuild all images

**Comment by MitchD42** [comment]
I just fresh installed it and I'm having the same Web GUI issue, the password keeps failing on me.

**Comment by MitchD42** [comment]
If you are running this on a VM and then accessing it from your local computer the login appears to be because of the redirect.

Here's ChatGPT's info to adjust the vite.config.ts file, instead of the BACKEND_URL you put the actual external IP address of your VM.
"Update the target property under proxy to the VM's IP address and port, like so:

typescript
Copy code
server: {
  proxy: {
    '/api': {
      target: 'http://[VM-IP-ADDRESS]:8090',
      changeOrigin: true,
      rewrite: (path) => path.replace(/^\/api/, ''),
    }
  },
},
Replace [VM-IP-ADDRESS] with the actual IP address of your VM."

**Comment by ChengFai** [comment]
OK sir. 
It seems like a bug or something in Vite.js caused this error

try this.
``` javascript

  server: {
    proxy: {
      '/api': BACKEND_URL_LOCALDEPLOY,
    },
    // proxy: {
    //   '/api': {
    //     target: BACKEND_URL_LOCALDEPLOY + port,
    //     changeOrigin: true,
    //     rewrite: (path) => path.replace(/^\/api/, ''),
    //   }
    // },
  },
```
